<template>
  <div>
    <div class="d-flex justify-content-between align-items-center position-relative">
      <div>
        Two-Factor Authentication:
        <strong>
          <i>{{account.profile.info.is2FAEnabled==="true"?"Enabled":"Disabled"}}</i>
        </strong>
      </div>
      <b-button
        v-if="account.profile.info.is2FAEnabled==='true'"
        variant="primary"
        @click="onBeforeDisabling2Fa"
        :disabled="isDisabling"
      >Disable</b-button>
      <b-button
        v-else
        variant="primary"
        @click="$emit('enable2Fa')"
        :disabled="account.twoFa.enabled"
      >Enable</b-button>
      <v-loading v-if="account.twoFa.enabling" />
    </div>
    <div v-if="account.twoFa.enabled" class="position-relative">
      <div class="mt-3 text-center">Scan this code with the security app on your device.</div>
      <div class="text-center">
        <img :src="account.twoFa.imgUrl" alt />
      </div>
      <div class="text-center">Then enter the 6-digit verification code generated by the app.</div>
      <b-col md="4" offset-md="4" sm="10" offset-sm="1" xs="12" offset-xs="0" class="mt-3">
        <b-form @submit.prevent="submit" autocomplete="off">
          <b-form-input
            autofocus
            id="verificationCode"
            type="text"
            placeholder="000000"
            aria-describedby="input-code-feedback"
            class="text-center"
            size="lg"
            v-model="verificationCode"
            @input="onVerificationCodeChange"
            :state="isCodeValid"
          ></b-form-input>
          <b-form-invalid-feedback id="input-code-feedback">Must be a 6-digit code.</b-form-invalid-feedback>
          <b-button variant="primary" class="w-100 mt-3" size="lg" type="submit">Enable 2FA</b-button>
        </b-form>
      </b-col>
      <div class="mt-3 text-center" v-if="account.twoFa.confirmingError">
        <span class="text-danger">{{account.twoFa.confirmingError.message}}</span>
      </div>
      <v-loading v-if="account.twoFa.confirming" />
    </div>
    <div v-if="isDisabling" class="position-relative mt-5">
      <div class="text-center">Enter the 6-digit verification code generated by your security app.</div>
      <b-col md="4" offset-md="4" sm="10" offset-sm="1" xs="12" offset-xs="0" class="mt-3">
        <b-form @submit.prevent="submit" autocomplete="off">
          <b-form-input
            autofocus
            id="verificationCode"
            type="text"
            placeholder="000000"
            aria-describedby="input-code-feedback"
            class="text-center"
            size="lg"
            v-model="verificationCode"
            @input="onVerificationCodeChange"
            :state="isCodeValid"
          ></b-form-input>
          <b-form-invalid-feedback id="input-code-feedback">Must be a 6-digit code.</b-form-invalid-feedback>
          <b-button variant="primary" class="w-100 mt-3" size="lg" type="submit">Disable 2FA</b-button>
        </b-form>
      </b-col>
      <div class="mt-3 text-center" v-if="account.twoFa.disablingError">
        <span class="text-danger">{{account.twoFa.disablingError.message}}</span>
      </div>
      <v-loading v-if="account.twoFa.disabling" />
    </div>
  </div>
</template>

<script>
export default {
  name: "enable-2fa",
  props: {
    account: {
      type: Object,
      required: true
    },
    disable2Fa: {
      type: Function
    }
  },
  data() {
    return {
      isCodeValid: null,
      verificationCode: "",
      isDisabling: false
    };
  },
  methods: {
    async submit() {
      if (this.verificationCode.length === 6) {
        if (!this.isDisabling) {
          await this.$emit("confirm2Fa", this.verificationCode);
        } else {
          await this.disable2Fa(this.verificationCode);
          if (!this.account.twoFa.disablingError) {
            this.isDisabling = false;
          }
        }
        this.verificationCode = "";
      } else {
        this.isCodeValid = false;
      }
    },
    async onVerificationCodeChange(value) {
      if (!value) {
        return (this.isCodeValid = null);
      }
      if (isNaN(Number(value)) || value.length > 6) {
        return (this.isCodeValid = false);
      }
      this.isCodeValid = null;
    },
    onBeforeDisabling2Fa() {
      this.isDisabling = true;
    }
  }
};
</script>