version: "3.3"

services:
  vault:
    image: vault
    env_file: app.env
    volumes:
        - ./vault/config:/vault/config
        - ./vault/policies:/vault/policies
        - ./vault/data:/vault/data
    ports:
      - "8200:8200"
  server:
    image: valk-server
    env_file: app.env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - vault
    ports:
      - "5001:3001"