version: '3.3'

services:
  health:
    image: "${APM_IMAGE}"
    env_file: app.env
    command: ["health", "--node", "${NODE_HOST}", "--production", "--prod-config-file", "/core/config.json"]
    network_mode: "host"
    depends_on:
      - sync
    volumes:
      - ${PROD_CONFIG_FILE}:/core/config.json

  sync:
    image: "${APM_IMAGE}"
    env_file: app.env
    network_mode: "host"
    command: ["sync", "--node", "${NODE_HOST}", "--production", "--prod-config-file", "/core/config.json"]
    volumes:
      - ${PROD_CONFIG_FILE}:/core/config.json

  server:
    image: "${APM_IMAGE}"
    env_file: app.env
    ports:
      - "3000:3000"
    network_mode: "host"
    command: ["server", "--node", "${NODE_HOST}", "--production", "--prod-config-file", "/core/config.json"]
    depends_on:
      - sync
      - monit
    volumes:
      - ${PROD_CONFIG_FILE}:/core/config.json

  monit:
    image: "${APM_IMAGE}"
    env_file: app.env
    network_mode: "host"
    command: ["monit", "--node", "${NODE_HOST}", "--production", "--prod-config-file", "/core/config.json"]
    depends_on:
      - sync
    volumes:
      - ${PROD_CONFIG_FILE}:/core/config.json
